#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation without documentation by default
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Compile OpenFOAM libraries and applications
src/Allwmake $targetType $*

# Compile OpenFOAM libraries and applications
applications/Allwmake $targetType $*


#------------------------------------------------------------------------------
